### ISSUE TITLE
PlantUML research

### ISSUE THREAD

**Issue by DaniBAIG7** [Arquisoft/radarin_en1b#10]
_This issue is intended to be kind of a glossary for PlantUML commands and concepts_
For creating the attached diagram
![image](https://user-images.githubusercontent.com/60442791/107495487-6fcb7700-6b90-11eb-85d7-3765469c5735.png)
I used the following code:
`:User: --> [User's Pod]: interacts
[User's Pod] - [Main App]: exchange information`

- :<name>: is used to create Actors.
- [<name>] is used to create Components
- Relationships are specified via arrows. '-' represents a bidirectional relationship, '-->' represents a unidirectional relationship

**Comment by albertodb99** [comment]
I want to add this link: https://plantuml.com/es/sequence-diagram , which is concrete for sequence diagram, whose syntax differ a little with the diagram of the first post.
