### ISSUE TITLE
Problem connecting mobile app with mongo db

### ISSUE THREAD

**Issue by ghost** [Arquisoft/radarin_en1b#108]
We are having some troubles to make the connection between the mobile application and the MongoDB from MongoDB Atlas, failing to fetch we think due to the api end point.
![image](https://user-images.githubusercontent.com/60443508/114480547-07862980-9c03-11eb-92f6-37f1ebcb9b62.png)

**Comment by pglez82** [comment]
Have you tested if the endpoint works? You can test that using a program like [postman](https://www.postman.com/product/api-client/). Make sure that the api works and then that code should work (it is very similar to the one that is in radarin_0 and that one is working).

If the error is in heroku you can login into mongo atlas with the same username and password than heroku to see what is going on.

**Comment by albertodb99** [comment]
In local it works, the problem come when it is online, that an error showing that http or https is needed in the header of the request.

**Comment by albertodb99** [comment]
![image](https://user-images.githubusercontent.com/60233035/114514365-7a12fb80-9c3b-11eb-82f3-a4bc5bddd1b5.png)
