### ISSUE TITLE
Adoc format research

### ISSUE THREAD

**Issue by uo269412** [Arquisoft/radarin_en1b#11]
In this issue we will leave different information about the adoc format, to make it easier to understand and faster to find.

**Comment by DaniBAIG7** [comment]
I found yesterday some commands that should be useful when working with .adoc, yet they don't seem to work when generated.
- "==" Seems to classify the different headings (similar to tags h1, h2... hN in HTML) depending on the number of "=" signs
-  "*" Seems to be the indicator of the different elements inside a list (like tag li)
-  "_" Can be useful to alter text. It can be used to make sections cursive (f.e. in "_section_", section would be cursive)

**Comment by uo269412** [comment]
_This is just a quick and small document to consult what might be the things that we will use the most_

### Paragraphs

To write paragraphs, no specific notation is needed. Although if we want  to make a paragraph larger, we can use [.lead] prior to writing the line. This will make that paragraph have a bigger font.

### Text format

- **Bold:** In order to make the font bold in a specific part of the text, we will write two *, encapsulating the words we want.
- **Cursive:** In order to make the font cursive in a specific part of the text, we will write two _, encapsulating the words we want.
- **Highlighting:** Text can be highlighted if we encapsulate the words between #.

These formats can be mixed to obtain a text with a specific format.

### Links

Links are provided automatically, but nevertheless, if we want to customize a link (we want to access google but not by clicking in the full URL, but in a reduced String), we can write:
_url_[name we want to provide]

### Sections

Different types of headers (like the typical h1, h2, h3) are also provided by using a different number of = prior to the text. The lower the level, the bigger the font

- **Level 0:** Provided by writing = before the text.
- **Level 1:** Provided by writing  == before the text.
- **Level 2:** Provided by writing  === before the text.
- **Level 3:** Provided by writing  ==== before the text.
- **Level 4:** Provided by writing  ===== before the text.
- **Level 5:** Provided by writing  ====== before the text.

### Lists

To specify lists and their items, different numbers of * prior to the text are used. By using this, we can nest different list items. The levels specify how nested is that item of the list, being the lower, the less nested.

- **Level 1:** Provided by writing * before the text.
- **Level 2:** Provided by writing  ** before the text.
- **Level 3:** Provided by writing  *** before the text.
- **Level 4:** Provided by writing  **** before the text.
- **Level 5:** Provided by writing  ***** before the text.

_If we want to create a regular list, with all the items having the same relevance, we should use the same number of * (normally just one). However, if we want to divide an element of the list in different elements, such elements will use one more * (the illusion of having a list within the list)_

- If we want to make an **ordered list**, we replace the * with .
- If we would like to use a **checked list**, we will use [*] to mark checked items and [ ] to those who don't.

To create a kind of **definition list**(think about the definition of a word in a dictionary), we will write the text like _word_we_want_to_define_ :: definition.

_All these formats can be mixed to create complex lists with different properties._

### Tables

To write tables we will use the given format:

.Table Title
|===
|Column 1, Header Row |Column 2, Header Row 

|Cell in column 1, row 1
|Cell in column 2, row 1

|Cell in column 1, row 2
|Cell in column 2, row 2
|===

_We can increment the number of rows and columns to have more cells in the table_

### Images

To insert images we will write image :: _file_name.extension_



_Most of the information provided here was consulted in the webpage https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/_

**Comment by UO266499** [comment]
In case you prefer seeing the syntax used with examples, this is a very in depth tutorial with both the code and the result. It is a little long, but also includes tips and tricks when working with this format.
Video: https://www.youtube.com/watch?v=KbmpBZO4EoY.
