### ISSUE TITLE
RestAPi deployment not working in heroku

### ISSUE THREAD

**Issue by albertodb99** [Arquisoft/radarin_en1b#112]
![image](https://user-images.githubusercontent.com/60233035/114538524-c5d19f00-9c53-11eb-8d05-c0c8878f6397.png)
Without doing nothing, the deployment of the RestAPI in Heroku stays the same, but the code in local works, so this error should not be happening... can someone help?

**Comment by albertodb99** [comment]
![image](https://user-images.githubusercontent.com/60233035/114543207-29aa9680-9c59-11eb-9fe7-834a8db52e4c.png)
After logging what it was receiving as mongo connection, this was obtained

**Comment by albertodb99** [comment]
But when trying to establish a mongo connection from atlas, this is our connection string:
![image](https://user-images.githubusercontent.com/60233035/114543390-6d050500-9c59-11eb-8313-4134091d0d43.png)
@pglez82 should we change the secret then?

**Comment by pglez82** [comment]
It doesn't make sense to me to change the secret if the database, mongo user and password didn't change. What I would do is change the connection string locally (replace mongodb://localhost:27017) to the one that you are logging to see if you get the same error locally. Then we can test things faster. If it also fails locally, find out the proper connection string and once it works locally against the mongo cloud db, update the secret with the new value. It should work the same in heroku.

**Comment by albertodb99** [comment]
There was a mistake with the password, it was changed yesterday, now it deploys correctly, and it works fine with our mobile application. Thanks Pablo! :)
