### ISSUE TITLE
Testing the SOLID login

### ISSUE THREAD

**Issue by DaniBAIG7** [Arquisoft/radarin_en1b#126]
We are having trouble trying to check the login with SOLID. Since our web application redirects us to the Inrupt login, we don't know how this could be tested in our unitary tests.

**Comment by pglez82** [comment]
@DaniBAIG7 , the idea here in unitary tests, it to mock the api calls (the same with solid), so we simulate the return values of those calls and we can execute the unitary tests without problems. There is a lot of information on the Internet about mocking api calls using jest. For instance, in the official documentation: https://jestjs.io/docs/mock-functions#mocking-modules
