### ISSUE TITLE
New errors found when testing

### ISSUE THREAD

**Issue by UO266499** [Arquisoft/radarin_en1b#129]
We have two new errors:
- First Error:
~When using the application as a new users, the file favlocations.ttl is created, but empty.~
~getThing() doesn't return the thing associated with the file from the POD correctly.
When trying to access the map or add new locations the error Expected a thing but received null appears.~

~- Second Error:
When Loading the map, this loads even before the reply from the window is sent, so the map loads before accepting or declining.~

This HAS to be solved ASAP!
I will post further information in responses if needed.

**Comment by UO266499** [comment]
Im currently working on the map loading situation, and will inform if anything pops up.

**Comment by UO266499** [comment]
In regards to the Map loading issue, when adding the friend obtaining part, the condition to wait for geolocation was removed and not added back. I changing the map and seeing if its fixed.

**Comment by UO266499** [comment]
The map loading error has been fixed, all it needed was a hook checking that the geolaction was accepted!
Im crossing the error so nobody gets confused.

**Comment by DaniBAIG7** [comment]
Updates on the big error:

It is kinda solved but a new, worse error arised. This has to do with the getThing method in the inrupt API. We are currently using it as `getThing(<resource associated with the POD file URL>, <URLof the file in the POD whose thing we want to obtain>)` (take in count that the resource was correctly retrieved earlier). This getThing seems to return a null value. This might have to do with the structure of the locations in the POD that we will use from now on.

Our previous structure (which worked but implied the original problem of the issue) was the following:
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/60442791/116218945-57103d80-a74b-11eb-8428-a2ed9de5d8e3.png)

And our current structure is:
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/60442791/116219000-68594a00-a74b-11eb-857a-74a24a822c2e.png)

We are a little bit lost at this point, help needed!!

**Comment by DaniBAIG7** [comment]
Solved the second problem of the POD Thing!!

Problem was that texts are treated as things when we directly access some POD file. Thus we must access them with the getThingAll method and then obtain their String with getThingNoLocale(). Before, we were trying to get an individual Thing of the favlocations.ttl and access its texts.
This is the code:
![image](https://user-images.githubusercontent.com/60442791/116230717-487c5300-a758-11eb-8498-590b16694636.png)
