### ISSUE TITLE
Branches & Pull requests

### ISSUE THREAD

**Issue by ghost** [Arquisoft/radarin_en1b#13]
We have been discussing about how to develop the documentation, including the structure of the **branches** and their associated **pull requests** between them.

Our best option is to create two types of branches:

- One for each of the 12 parts that compose the entire documentation.
- And another one for each one of the collaborators in this repository.

As at this moment 2 people have been assigned to each of the 3 first sections, the idea would be to start creating content each one in his own branch, creating a pull request when trying to merge to the branch where the new information belongs to, putting as reviewer to your corresponding partner. After that, when a part gets finished, a new pull request has to be generated in order to put it into master, but this time assigning the revision to people that have not been doing this part of the documentation, so this way it is easier for every team member to know how the full work is going on!

**Comment by uo269412** [comment]
This is perfect! Thank you very much! Having this around will help avoiding possible errors if we miss a step
