### ISSUE TITLE
Problem with dependency on section 3 diagram

### ISSUE THREAD

**Issue by DaniBAIG7** [Arquisoft/radarin_en1b#20]
The PlantUML diagram used in Section 3 is giving some problem in Heroku, although it seems to work locally.

**Comment by DaniBAIG7** [comment]
The diagram seems to be using something that wasn't initially added in Heroku. Something that might solve it is adding the command `RUN apt install graphviz` to the docker file, since installing that package locally seems to make it work.

**Comment by Rcenador** [comment]
Have you tried adding @startuml and @enduml at the beginning and end of your PlantUML code?

In your case it would look something like:

@startuml  
:User1: --> [User1's Pod]: interacts    
[User1's Pod] --> [Main App]: Send location    
[Main App] --> [User1's Pod]: Manages    
:User2: --> [User2's Pod]: interacts  
[User2's Pod] - [User1's Pod]: send notifications  
[User2's Pod] --> [Main App]: Send location  
[Main App] --> [User2's Pod]: Manages  
@enduml

**Comment by UO266499** [comment]
Thanks for the insight we wil take it into account for further development, however, we forgot to close the issue a couple days ago after Pablo helped us resolve the issue. Thanks for reviewing our work!
