### ISSUE TITLE
5. Building Block View

### ISSUE THREAD

**Issue by UO266499** [Arquisoft/radarin_en1b#22]
The building block view shows the static decomposition of the system into building blocks (modules, components, subsystems, classes, interfaces, packages, libraries, frameworks, layers, partitions, tiers, functions, macros, operations, datas structures, …​) as well as their dependencies (relationships, associations, …​)

This view is mandatory for every architecture documentation. In analogy to a house this is the floor plan.

Form as seen below:
![imagen](https://user-images.githubusercontent.com/61158846/108059205-72791100-7055-11eb-997a-eb4b59d368d1.png)

**Comment by uo269412** [comment]
### Revision of the documentation prototype

### _Regarding_ 5.1

Add a link from mobile application to web application (locations are stored in the web, not in the pod)
Allow the user to see the locations and delete the ones they don't want (from the web application)
