### ISSUE TITLE
10. Quality Requirements

### ISSUE THREAD

**Issue by UO266499** [Arquisoft/radarin_en1b#27]
This section contains all quality requirements as quality tree with scenarios. The most important ones have already been described in section 1.2. (quality goals)

Here you can also capture quality requirements with lesser priority, which will not create high risks when they are not fully achieved.

**Comment by uo269412** [comment]
These are some of the quality changes that we thought about and we are planning to add in the documentation:

- The application can create a route from a set of different locations. This route may have a description stablishing what is its main appeal and the locations that should be visited.
- A planification feature, where you can stablish that you're going to visit a location today, so your friends can see that you are going and decide that they are going too and meet there.
- Ratings on each location, all the users can vote whether they like the location or not when they are nearby (one vote per person) so if the location is popular, it will be suggested more.
- A history feature for each profile (may be private or can be public to friends) in which all the visited locations are stored in a diary kind of way.
- A recommended feature for each profile, in which users may recommend specific locations to the users of the application
- An achievement system for the users to obtain. Visiting locations or using the application, the user may gain different titles or options to display in their profile.
