### ISSUE TITLE
Technical context diagram: Do you like it?

### ISSUE THREAD

**Issue by DaniBAIG7** [Arquisoft/radarin_en1b#30]
I built a diagram in order to show the Technical Context of the application. Do you think it covers the technical aspects so far?
![image](https://user-images.githubusercontent.com/60442791/108085473-a95f1f00-7075-11eb-9006-34b0aeae6c19.png)

I did it basing on this piece of documentation (although mine is way less detailed):
[https://biking.michael-simons.eu/docs/index.html#_technical_context](url)

**Comment by uo269412** [comment]
I think that so far it might work (given that it's a prototype and we have the option to extend it later as we see how the application should work)

**Comment by UO266499** [comment]
I agree with @uo269412,it's also easy to understand, which is specially useful now that we haven't gone in depth. We can add to it later on once we know the finer details.

**Comment by albertodb99** [comment]
I agree too! It is very easy to understand the context, at least for me, and I am sure that it will be easy to maintain while we extend the application

**Comment by DaniBAIG7** [comment]
This issue is going to be closed since in the review of the documentation we discovered that it was not the kind of diagram expected to appear in the technical context. Furthermore, most documentations do not use diagrams to illustrate the technical context, so we will rely on the table to explain the technical concepts involved in the application.
