### ISSUE TITLE
Bug regarding deployment in Heroku

### ISSUE THREAD

**Issue by UO266499** [Arquisoft/radarin_en1b#52]
Error when deploying the app in heroku regarding graphviz:

Error: Command failed: heroku container:push web --app radarinen1bwebapp --arg API_URI="https://radarinen1brestapi.herokuapp.com/api" › Warning: heroku update available from 7.47.12 to 7.47.13. The command '/bin/sh -c apt install graphviz' returned a non-zero code: 1 ▸ Error: docker build exited with Error: 1

**Comment by pglez82** [comment]
Duplicate of #53
