### ISSUE TITLE
Error deploying the documentation

### ISSUE THREAD

**Issue by uo269412** [Arquisoft/radarin_en1b#53]
This deployment is not working due to an error related to heroku. This is a fragment related to the error:

Run akhileshns/heroku-deploy@v3.8.9
Created and wrote to ~/.netrc
 ›   Warning: Our terms of service have changed: 
 ›   https://dashboard.heroku.com/terms-of-service
heroku: Press any key to open up the browser to login or q to exit:  ›   Warning: heroku update available from 7.47.12 to 7.48.0.
Successfully logged into heroku
WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

 ›   Warning: heroku update available from 7.47.12 to 7.48.0.
Added git remote heroku
 ›   Warning: heroku update available from 7.47.12 to 7.48.0.
The command '/bin/sh -c apt install graphviz' returned a non-zero code: 1
 ▸    Error: docker build exited with Error: 1

            Unable to push branch because the branch is behind the deployed branch. Using --force to deploy branch. 
            (If you want to avoid this, set dontuseforce to 1 in with: of .github/workflows/action.yml. 
            Specifically, the error was: Error: Command failed: heroku container:push web --app radarinen1bwebapp --arg API_URI="https://radarinen1brestapi.herokuapp.com/api"
 ›   Warning: heroku update available from 7.47.12 to 7.48.0.
The command '/bin/sh -c apt install graphviz' returned a non-zero code: 1
 ▸    Error: docker build exited with Error: 1

        
 ›   Warning: heroku update available from 7.47.12 to 7.48.0.
The command '/bin/sh -c apt install graphviz' returned a non-zero code: 1
Error: Error: Command failed: heroku container:push web --app radarinen1bwebapp --arg API_URI="https://radarinen1brestapi.herokuapp.com/api"
 ›   Warning: heroku update available from 7.47.12 to 7.48.0.
The command '/bin/sh -c apt install graphviz' returned a non-zero code: 1
 ▸    Error: docker build exited with Error: 1

 ▸    Error: docker build exited with Error: 1

**Comment by pglez82** [comment]
This issue shouldn't be closed as it is not fixed yet.

**Comment by pglez82** [comment]
Fixed in 01d5b3ecc54355e7473d144b42783a33f3c0657a.
You can close this issue now and the duplicated one once you check that everything is correct.
