### ISSUE TITLE
Something strange happened when including the bootstrap dependency

### ISSUE THREAD

**Issue by DaniBAIG7** [Arquisoft/radarin_en1b#64]
The console said something about a peer dependency. I didn't install those, so we should take this warning into account;  It could be the source of further errors.

![image](https://user-images.githubusercontent.com/60442791/109660903-a9791780-7b69-11eb-9f4f-0362c013588e.png)

**Comment by pglez82** [comment]
I wont worry to much about that. It seems to be an optional dependency.
Pablo
