### ISSUE TITLE
Problem when compiling the react application (branch webapplication-developing-daniel)

### ISSUE THREAD

**Issue by DaniBAIG7** [Arquisoft/radarin_en1b#65]
I found some code online to include Google Maps in react, so I tried copying it to include it in my code and adapt it to our necessities.
Problem is that although I think that I downloaded and installed the necessary dependencies properly, I get an error (at the end of the attached photo) that I can't manage to solve although I searched a lot on the web. This problem didn't happen on the default application, so I must have done something to cause it.

![image](https://user-images.githubusercontent.com/60442791/109717142-f7137580-7ba5-11eb-930a-ab801e31d43a.png)

**Comment by DaniBAIG7** [comment]
Regarding the attached code, I have another question, because I don't understand something about it ([webpage where I extracted it from](https://www.mindbowser.com/react-google-map-with-a-custom-pin-marker/))
When declaring the Map component, the google attribute is being assigned some value stored in "this.props.google". Where are those properties stored? In the component superclass?

**Comment by pglez82** [comment]
Please Dani, push your code to the repo in a new branch so we can reproduce your error and fix it. Thanks!

**Comment by DaniBAIG7** [comment]
> Please Dani, push your code to the repo in a new branch so we can reproduce your error and fix it. Thanks!

Sorry I didn't see the message... Is already on my personal branch, the one in the title, "webapplication-developing-daniel".
Just in case, I'm going to create another one.

**Comment by DaniBAIG7** [comment]
I just created it. It's called "issue-65-problem"

**Comment by UO266499** [comment]
Found the problem, when importing React, you typed:
import React, { Component } from 'React'
instead of: 
import React, { Component } from 'react'

React is with lower case r.

**Comment by DaniBAIG7** [comment]
Thank you!
