### ISSUE TITLE
ADB problem when running npx react-native run-android

### ISSUE THREAD

**Issue by albertodb99** [Arquisoft/radarin_en1b#66]
When running npx react-native run-android I get the following error:
![image](https://user-images.githubusercontent.com/60233035/110168615-bad75380-7df7-11eb-835b-a7cb24a65a17.png)
My android_home path is configured correctly, and this is not corrected after trying to change it.

**Comment by pglez82** [comment]
Hi,

There is more to configure than the android_home variable. Check [here](https://stackoverflow.com/q/29391511/2828454).
After configuring the environment variables and setting the path accordingly, I was able to run without problems:

```bash
npx react-native init basicapp
cd basicapp
npm start #This launchs the metro server
npm run android #this is equivalent to  npx react-native run-android (see package.json)
```

One last thing is that I think you need to have an emulator created, so the app can launch in this emulator.

Pablo

**Comment by pglez82** [comment]
@uo266536 can you tell us if that solved your problem or not? This way others can use this information.

Pablo
