### ISSUE TITLE
Problem with react-leaflet (branch-issue-68)

### ISSUE THREAD

**Issue by DaniBAIG7** [Arquisoft/radarin_en1b#68]
We decided to change the API used for the maps. Instead of Google Maps, now we will try to use react-leaflet, which simplifies a lot  the task of adding PopUps to markers. The problem is that something is going wrong when executing the app.

![image](https://user-images.githubusercontent.com/60442791/110503241-47d22380-80fc-11eb-9522-102662a873c1.png)

It is a very strange error, and it's strange that the code fails since I took a lot of that code from the [react-leaflet sample on how to implement a map with a popup](https://react-leaflet.js.org/docs/example-popup-marker)

The code can be found on branch `branch-issue-68`

**Comment by pglez82** [comment]
Hi, 
I can not reproduce it. I get this.
![image](https://user-images.githubusercontent.com/10683040/110523910-06993e00-8113-11eb-905d-fdfe605274ba.png)

Any idea?
Pablo

**Comment by UO266499** [comment]
I was debugging the code and it appears to be due to the parseFloat(...) in the   const position = [parseFloat(this.latitude), parseFloat(this.longitude)];
Both of them return NaN instead of a value.

**Comment by DaniBAIG7** [comment]
Alex managed to solve it (it was difficult, but it's done)
