### ISSUE TITLE
2. Constraints

### ISSUE THREAD

**Issue by uo269412** [Arquisoft/radarin_en1b#7]
"Anything that constrains teams in design and implementation decisions or decision about related processes. Can sometimes go beyond individual systems and are valid for whole organizations and companies."

Specifications about the constraints and decisions taken regarding to the assignment. This will affect the freedom of design and will structure the development process.

**Comment by ghost** [comment]
I would like to drop here one thing the theory teacher, Jose Labra, told us in today's class, and it is that we have to be careful when looking at documentations of previous year, in which _React_ is set as a constraint, but it **is not** when dealing with our assignment. However, for example _Solid_ **is** a constraint we must keep in mind.

**Comment by ghost** [comment]
In today's lab, the teacher reviewed the current documentation of the project and he told us that heroku itself is not a technical constraint, but the deployment in a cloud service (like heroku).

**Comment by uo269412** [comment]
### Revision of the documentation prototype

### _Regarding_ 2.2

Add new constraint -> Work remotely.

**Comment by ghost** [comment]
Done by @luisfesu.
