### ISSUE TITLE
Mobile application deployment

### ISSUE THREAD

**Issue by ghost** [Arquisoft/radarin_en1b#71]
In the previous checkpoint, we were said that everything must be deployed, in Heroku for example. However, we do not know how the mobile application can be deployed. At this moment, it is published in Expo (https://expo.io/@uo266536/projects/asw-radarin_en1b), where it is possible to scan a QR code to load the project in your phone and see how it is working, but we are not sure if this is enough.

**Comment by pglez82** [comment]
Yes, it is enough. The mobile application with react native cannot be deployed to Heroku so using another way to publish it seems fine.

Pablo
