### ISSUE TITLE
Problems with codacy

### ISSUE THREAD

**Issue by DaniBAIG7** [Arquisoft/radarin_en1b#75]
Some members of the group (including myself) are having some trouble with Codacy when creating pull requests. In my case, this is the log of the error:
![image](https://user-images.githubusercontent.com/60442791/111080988-6a4fac80-8501-11eb-9192-71afd39bc0b1.png)
Since it says that the branch is not being analyzed, should we just leave that error and do the pull requests anyway?

**Comment by luisfesu** [comment]
I have the same problem with Codacy. The errors seem to be related with line-endings:
![errores codacy](https://user-images.githubusercontent.com/58345609/111081130-15f8fc80-8502-11eb-9217-4175f16e817d.jpg)

This entry in the codacy documentation talks about it, but I can't find the solution:
[Codacy: error-line-endings](https://docs.codacy.com/faq/troubleshooting/error-line-endings/)

**Comment by pglez82** [comment]
Codacy is a tool for the static analysis of the code. Currently is configured to analyze only the master branch. So the warning is normal. In session 8 (next week) we are going to talk a little bit more about these tools.

If you want to configure codacy, you should be able to login into codacy.com using your github account. There you should be able to find the repository and configure how codacy analyzes it.
