### ISSUE TITLE
Problem related to logging in Mongo DB

### ISSUE THREAD

**Issue by uo269412** [Arquisoft/radarin_en1b#82]
We are having an issue trying to log into the Mongo DB web page since it asks for an authentication.  Since we don't have access to the mobile linked, we're stucked here. Help is appreciated.

![image](https://user-images.githubusercontent.com/60443414/112144282-482ced00-8bd9-11eb-8e33-1b11def681f9.png)

**Comment by pglez82** [comment]
I really do not know what is the best solution here. I think I have created the account using my phone so maybe the code gets to me. I can send it to you by private message in teams or maybe I can add your phone number to the account so the code gets to you directly. If you decide for that option, talk to me in teams and we can try to fix it.
