### ISSUE TITLE
Problem with technology "query-idflex"

### ISSUE THREAD

**Issue by DaniBAIG7** [Arquisoft/radarin_en1b#83]
The team that works on the web application is having trouble with obtaining information from the POD's. More precisely, with the "query-idflex" technology. We don't know why, but the expressions used in the related [GitHub page documentation](https://solid.github.io/query-ldflex/#usage) seem to not work, and we don't know which alternative we could choose in order to extract information from a POD.

For example, to extract the name from the POD we could use this expression:
![image](https://user-images.githubusercontent.com/60442791/112883533-b3d9f300-90ce-11eb-9d38-273e838d1e18.png)
But if we run it in the app, we get the name undefined. Also, we cannot understand why do they use the "solid" part of the query, since we don't know where to import that module from.

**Comment by pglez82** [comment]
Daniel, check the issue that I referenced above. Probably it will help you out solving your problem.

**Comment by DaniBAIG7** [comment]
@pglez82 In the end I decided to use the inrupt API, although it was difficult, I think that with the help of a member of another group I managed to solve it
