### ISSUE TITLE
Problem compiling react application

### ISSUE THREAD

**Issue by DaniBAIG7** [Arquisoft/radarin_en1b#85]
We had a problem trying to integrate the POD reading technology to the application. React won't compile it since it detects too many hooks on a certain point of the app, i think. The exact error is the following:
![image](https://user-images.githubusercontent.com/60442791/113430667-d293fe80-93da-11eb-8eba-c689b340014d.png)
The code with the failure is in the branch [webapplication-developing-issue-85](https://github.com/Arquisoft/radarin_en1b/tree/webapplication-developing-issue-85)

**Comment by UO266499** [comment]
Found something that might be helpful, when inspecting the errors in the browser, i find thos warning:

Warning: React has detected a change in the order of Hooks called by App. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useState                   useState
2. useContext                 useContext
3. useState                   useState
4. useState                   useState
5. undefined                  useContext
 
Im going to read about it some more and see what i can find/fix.

**Comment by UO266499** [comment]
Found something that might be helpful, when inspecting the errors in the browser, i find thos warning:

Warning: React has detected a change in the order of Hooks called by App. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks
Previous render  -> Next render
    useState ->useState
    useContext ->useContext
    useState ->useState
    useState ->useState
    undefined ->useContext

Im going to read about it some more and see what i can find/fix.

**Comment by pglez82** [comment]
Could this be helpful?: https://stackoverflow.com/questions/57397395/react-has-detected-a-change-in-the-order-of-hooks-but-hooks-seem-to-be-invoked

**Comment by DaniBAIG7** [comment]
I solved it with that, thank you. I leave the issue open since Solid PODs are still giving some problems and I want to take care of them in the branch assigned to this issue
