### ISSUE TITLE
SOLID research

### ISSUE THREAD

**Issue by uo269412** [Arquisoft/radarin_en1b#9]
This issue will cover the different and interesting information we might find by researching the SOLID principal design.

**Comment by albertodb99** [comment]
Udemy tutorial (very interesting, but has to be paid):
https://www.udemy.com/course/solid-software-architecture-complete-guide-with-c-examples/

**Comment by DaniBAIG7** [comment]
Some information about Solid can be found at https://solidproject.org/about
For developers, there's also a begginers tutorial available in their webpage: https://solidproject.org/developers/tutorials/getting-started

**Comment by luisfesu** [comment]
useful Tim Berners-Lee  presentation about SOLID demostration: https://www.youtube.com/watch?v=gZB6d-4klmU
