### ISSUE TITLE
Cannot read from PODs in the web application

### ISSUE THREAD

**Issue by DaniBAIG7** [Arquisoft/radarin_en1b#90]
Although we managed to write to the different PODs in the mobile app, we still cannot read that information from the POD. We tried to follow the tutorial in the webpage https://www.freecodecamp.org/news/create-a-solid-to-do-app-with-react/ , which is pretty good, but we didn't manage to get the "thing" (with the getThing(...) function)
![Code image](https://user-images.githubusercontent.com/60442791/113753714-b6f86300-970e-11eb-8d90-96df703ba522.png)

Related code is on the branch [webapplication-developing-issue-85](https://github.com/Arquisoft/radarin_en1b/tree/webapplication-developing-issue-85), inside web-application/utils/getLocations.js

**Comment by albertodb99** [comment]
https://solid.github.io/developers/tutorials/getting-started this could also be really helpful, however, I am diving into it today and try to solve it.

**Comment by luisfesu** [comment]
I have exactly the same problem. I've been making some atempts to conect in this way to Solid to retrieve information from the POD's but apparently, the thing const remains as a null object after invoking the getThing() function.
![problema solid](https://user-images.githubusercontent.com/58345609/114050340-77f01c00-988c-11eb-8c87-11dcaf29b9b2.jpg)
 function.

**Comment by DaniBAIG7** [comment]
We already know why: We are using useEffect so that the locations are obtained when the component is rendered. The thing is that the component has not been rendered when we try to invoke getLocations:
![image](https://user-images.githubusercontent.com/60442791/114054835-7cb6cf00-9890-11eb-9171-6970b50f669d.png)
We are just passing the getLocations as props, but this means that useEffect has not been invoked, since the component is not rendered. We have to find a way to obtain that information before rendering. Ideas are welcome ;)

**Comment by albertodb99** [comment]
@pglez82 can you bring us some light?

**Comment by UO266499** [comment]
I'll give it another look, maybe change the approach to retreiving the info and ill reply as soon as i can make it work

**Comment by albertodb99** [comment]
The most recent changes are in the branch [webapplication--Alberto-location-and-friends](https://github.com/Arquisoft/radarin_en1b/tree/webapplication--Alberto-location-and-friends)

**Comment by pglez82** [comment]
I don't know if you tried it but usually we use the useEffect to make any of the api calls that we may need before the component renders and we store the result in the state. Then you can pass a prop using the state variable that have been populated with the useEffect hook.

I really do not know if thats the problem or not (didn't check the code). If you want me to look at the code let me know the branch and the file I should look.

**Comment by DaniBAIG7** [comment]
Yes, it is on the branch [webapplication-developing-issue-85](https://github.com/Arquisoft/radarin_en1b/tree/webapplication-developing-issue-85), in the file utils/GetLocations.js

**Comment by DaniBAIG7** [comment]
Now the problem has changed a bit, we solved the null stuff, but when we are trying to read from the POD we get an empty string with no location (although there is one on my POD).
If you want to add a location with our schema you can use the form in the branch [mobile-application-leafletlocations2](https://github.com/Arquisoft/radarin_en1b/tree/mobile-application-leafletlocations2) .
The problem is the following:
![image](https://user-images.githubusercontent.com/60442791/114268571-03d78480-9a02-11eb-95b0-2e6d6e1051f4.png)
(The array in the console log is empty)
And the locations in the POD have this format:
![image](https://user-images.githubusercontent.com/60442791/114268591-1fdb2600-9a02-11eb-831f-709b6cb0eae8.png)
The code is in the route stated in the previous comment

The problem is, specifically, the _getUrlAll(...)_ method from the solid inrupt library. It obtains no string.  If we try to get a single location, with the method _getStringNoLocale(...)_, it works, returning the first location stored.
![image](https://user-images.githubusercontent.com/60442791/114268806-61200580-9a03-11eb-8ea5-68d26103eadd.png)

**Comment by DaniBAIG7** [comment]
Solved, we were able to solve it using a method from the inrupt library: getStringNoLocaleAll(...)
